### ISSUE TITLE
Pod and SwiftPM have different module names

### ISSUE THREAD

**Issue by momja** [dadalar/SwiftUI-CardStackView#2]
When using Podfiles, you have to import as SwiftCardStackUI, while SwiftPM requires importing as CardStack.

**Comment by dadalar** [comment]
Good catch! There was already a pod named CardStack so I had to use another name for CocoaPods. Turns out we can still define the module name. Both CocoaPod and SPM will use CardStack on the next release.

**Comment by dadalar** [comment]
Fixed in version 0.0.4
